name: mc_cafe_app
description: "MC Cafe - A Taste Worth Savouring"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/banners/
    - assets/icons/
    - assets/icons/nav/
    - assets/logos/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora/static/Sora-Regular.ttf
        - asset: assets/fonts/Sora/static/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora/static/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora/static/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora/static/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora/static/Sora-ExtraBold.ttf
          weight: 800
